/**
 * Redux constants for News Redux
 * @author VIVEK PS
 */
const NEWS_REDUX_ACTION_TYPES = {
    FETCH_NEWS_DATA_REQUEST: 'FETCH_NEWS_DATA_REQUEST',
    FETCH_NEWS_DATA_RESPONSE: 'FETCH_NEWS_DATA_RESPONSE',
    FETCH_NEWS_DATA_ERROR: 'FETCH_NEWS_DATA_ERROR',
    FETCH_NEWS_DATA_CLEAR: 'FETCH_NEWS_DATA_CLEAR',

    RETRIEVE_NEWS_FROM_LOCAL_REQUEST: 'RETRIEVE_NEWS_FROM_LOCAL_REQUEST',
    RETRIEVE_NEWS_FROM_LOCAL_RESPONSE: 'RETRIEVE_NEWS_FROM_LOCAL_RESPONSE',
    RETRIEVE_NEWS_FROM_LOCAL_ERROR: 'RETRIEVE_NEWS_FROM_LOCAL_ERROR',
    RETRIEVE_NEWS_FROM_LOCAL_CLEAR: 'RETRIEVE_NEWS_FROM_LOCAL_CLEAR',

    UPDATE_NEWS_DATA_REQUEST: 'UPDATE_NEWS_DATA_REQUEST',
    UPDATE_NEWS_DATA_RESPONSE: 'UPDATE_NEWS_DATA_RESPONSE',
    UPDATE_NEWS_DATA_ERROR: 'UPDATE_NEWS_DATA_ERROR',
    UPDATE_NEWS_DATA_CLEAR: 'UPDATE_NEWS_DATA_CLEAR',
};

export default NEWS_REDUX_ACTION_TYPES;
