/**
 * Redux constants for News Redux
 * @author VIVEK PS
 */
const NEWS_REDUX_ACTION_TYPES = {
    FETCH_NEWS_DATA_REQUEST: 'FETCH_NEWS_DATA_REQUEST',
    FETCH_NEWS_DATA_RESPONSE: 'FETCH_NEWS_DATA_RESPONSE',
    FETCH_NEWS_DATA_ERROR: 'FETCH_NEWS_DATA_ERROR',
    FETCH_NEWS_DATA_CLEAR: 'FETCH_NEWS_DATA_CLEAR',
};

export default NEWS_REDUX_ACTION_TYPES;
